Version 1.4/ModelViewController/app/controllers/userData_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app, session
from flask_bcrypt import Bcrypt
from werkzeug.utils import secure_filename
import os

from app.models.userData_model import fill_user_profile , get_profile

userData = Blueprint('userData',__name__, url_prefix='/data')

@userData.route('/initial-data', methods=['GET', 'POST'])
def initialDataForm():

    connection = current_app.connection
    idUser = session.get('idUser')

    if not idUser:
        return redirect(url_for('userAuth.logIn'))
    
    if request.method == 'GET':
        if get_profile(connection,idUser):
            return redirect(url_for('userDb.user_dashboard'))
        return render_template('user/formInitialData.html')

    if request.method == 'POST':
        idUserSex = request.form['idUserSex']
        profileJobStartTime = request.form['profileJobStartTime']
        profileJobEndTime = request.form['profileJobEndTime']
        profileDailyFreeMinutes = request.form['profileDailyFreeMinutes']
        profileCurrentDiet = request.form['profileCurrentDiet']
        profileDailyFoodsAverage = request.form['profileDailyFoodsAverage']
        profileEstimatedDailyWaterLitres = request.form['profileEstimatedDailyWaterLitres']
        profileSleepTimeAverage = request.form['profileSleepTimeAverage']
        profileCurrentPhysicStatus = request.form['profileCurrentPhysicStatus']
        profileExerciseSessionsFrecuencyWeekly = request.form['profileExerciseSessionsFrecuencyWeekly']
        profileFavoriteExerciseType = request.form['profileFavoriteExerciseType']
        profileScreenTimeAverage = request.form['profileScreenTimeAverage']
        profileStressScale = request.form['profileStressScale']

        fill_user_profile(connection,idUser, idUserSex,profileJobStartTime,profileJobEndTime,profileDailyFreeMinutes,profileCurrentDiet,profileDailyFoodsAverage,profileEstimatedDailyWaterLitres,profileSleepTimeAverage,profileCurrentPhysicStatus,profileExerciseSessionsFrecuencyWeekly,profileFavoriteExerciseType,profileScreenTimeAverage,profileStressScale)
        return redirect(url_for('userDb.user_dashboard'))

    return render_template('user/formInitialData.html')

Version 1.4/ModelViewController/app/controllers/user_controller.py
# app/controllers/user_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app, session
from flask_bcrypt import Bcrypt
from werkzeug.utils import secure_filename
import os


userDb = Blueprint('userDb', __name__ , url_prefix = '/user')

@userDb.route('/dashboard', methods=['GET', 'POST'])
def user_dashboard():
    return render_template('user/userInterface.html')

@userDb.route('/yourData', methods = ['GET' , 'POST'])
def user_data():
    return render_template('user/userData.html')

@userDb.route('/yourGoals', methods = ['GET' , 'POST'])
def user_goals():
    return render_template('user/userGoals.html')

@userDb.route('/yourProgress', methods = ['GET' , 'POST'])
def user_progress():
    return render_template('user/userProgress.html')

@userDb.route('/yourReminders', methods = ['GET' , 'POST'])
def user_reminders():
    return render_template('user/userReminders.html')

Version 1.4/ModelViewController/app/templates/user/formInitialData.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/user/InitialData/FormInitialDataStyles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/footer.css') }}">
    <title>Datos Iniciales</title>
</head>
<body>





<div class="wrapper">
  <header>
    <div class = "cabecero">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <img src="{{ url_for('static', filename='uploads/main/header/whitemindsetlogo.png') }}" alt="">


            </div>
        </nav>
  </div>
             


  </header>

  <main class="container my-5">
    <form class="row g-3" method="post" action = "{{url_for('userData.initialDataForm')}}">
  <div class="col-md-6">
    <label for="profileJobStartTime" class="form-label">¿A qué hora empieza tu jordana laboral?</label>
    <input type="time" class="form-control" id="profileJobStartTime" name="profileJobStartTime"required>
  </div>
  <div class="col-md-6">
    <label for="profileJobEndTime" class="form-label">¿A qué hora finaliza tu jornada laboral?</label>
    <input type="time" class="form-control" id="profileJobEndTime" name = "profileJobEndTime" required>
  </div>

    <div class="col-md-6">
    <label for="profileDailyFreeMinutes" class="form-label">¿Cuántos tiempo libre en promedio tienes al día? (minutos)</label>
    <input type = "number" class = "form-control" id = "profileDailyFreeMinutes" name = "profileDailyFreeMinutes" required>
  </div>
    <div class="col-md-6">
    <label for="profileCurrentDiet" class="form-label">¿Qué tipo de dieta consideras que sigues actualmente? </label>
    <select id="profileCurrentDiet" class="form-select" name="profileCurrentDiet" required>
        <option selected>...</option>
        <option value = "Regular">Regular</option>
        <option value = "Ganar peso">Ganar peso</option>
        <option value = "Perder peso">Perder peso</option>
    </select>
  </div>

    <div class="col-md-6">
    <label for="profileDailyFoodsAverage" class="form-label">¿Cuántas comidas sueles tener al día?</label>
    <input type = "number" class = "form-control" id = "profileDailyFoodsAverage" name = "profileDailyFoodsAverage" required>
  </div>

<div class="col-md-6">
    <label for="profileEstimatedDailyWaterLitres" class="form-label">¿Qué cantidad de agua en promedio bebes al día? (litros)</label>
    <input type = "number" class = "form-control" id = "profileEstimatedDailyWaterLitres" name = "profileEstimatedDailyWaterLitres" step = "0.1" required>
  </div>
<div class="col-md-6">
    <label for="profileSleepTimeAverage" class="form-label">¿Cuánto tiempo sueles dormir al día? (horas)</label>
    <input type = "number" class = "form-control" id = "profileSleepTimeAverage" name = "profileSleepTimeAverage" step = "0.1" required>
  </div>
 
    <div class="col-md-6">
    <label for="profileCurrentPhysicStatus" class="form-label">¿Cómo consideras tu estado físico actual? </label>
    <select id="profileCurrentPhysicStatus" class="form-select" name="profileCurrentPhysicStatus" required>
        <option selected>...</option>
        <option value = "Principiante">Principiante</option>
        <option value = "Intermedio">Intermedio</option>
        <option value = "Avanzado">Avanzado</option>
    </select>
  </div>

    <div class="col-md-6">
    <label for="profileExerciseSessionsFrecuencyWeekly" class="form-label">¿Cuántas sesiones de ejercicio sueles practicar? (semanalmente)</label>
    <input type = "number" class = "form-control" id = "profileExerciseSessionsFrecuencyWeekly" name = "profileExerciseSessionsFrecuencyWeekly" required>
  </div>

    <div class="col-md-6">
    <label for="profileFavoriteExerciseType" class="form-label">¿Qué tipo de ejercicio consideras como tu favorito? </label>
    <select id="profileFavoriteExerciseType" class="form-select" name="profileFavoriteExerciseType" required>
        <option selected>...</option>
        <option value = "Relajacion">Relajacion</option>
        <option value = "Fuerza">Fuerza</option>
        <option value = "Cardio">Cardio</option>
        <option value = "Otro">Otro</option>
    </select>
  </div>

    <div class="col-md-6">
    <label for="profileScreenTimeAverage" class="form-label">¿Cuánto tiempo sueles estar frente a pantallas al día? (minutos)</label>
    <input type = "number" class = "form-control" id = "profileScreenTimeAverage" name = "profileScreenTimeAverage" required>
  </div>

    <div class="col-md-6">
    <label for="idUserSex" class="form-label">¿Cuál es tu sexo?</label>
    <select id="idUserSex" class="form-select" name="idUserSex" required>
        <option selected>...</option>
        <option value = "1">Masculino</option>
        <option value = "2">Femenino</option>
    </select>
  </div>

    <div class="col-md-12">
        <label for="profileStressScale" class="form-label">¿Cómo consideras tu nivel de estrés? (menos estrés -- mayor estrés)</label>
        <input type="range" class="form-range" min="0" max="10" id="profileStressScale" name="profileStressScale" required>
    </div>

    

      <div class="col-12">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="gridCheck" required>
          <label class="form-check-label" for="gridCheck">
            Autorizo el uso de mis datos
          </label>
        </div>
      </div>
      <div class="col-12 signUp-btn">
        <button type="submit" class="btn btn-primary signUp-buttom">Actualizar mis datos</button>
      </div>
</form>

  </main>
  <footer>
      <div class="container text-center footer-container">
        <div class="row header-signature">
          <div class="col"></div>
          <div class="col"></div>
          <div class="col"></div>
          <div class="col-end">Mindset © 2025</div>
        </div>
      </div>
  </footer>
</div>


</body>
<script src = "{{ url_for('static', filename = 'js/bootstrap.min.js') }} "></script>
</html>


























    

Version 1.4/ModelViewController/app/templates/user/userData.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/user/stylesUserInterface.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/footer.css') }}">
    <title>Tus datos</title>
</head>
<body>

 <div class="wrapper">
  <header> 
    <div class = "cabecero">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <img src="{{ url_for('static', filename='uploads/main/header/whitemindsetlogo.png') }}" alt="">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_dashboard') }}"> Tu inicio</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_data')}}">Tus datos</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_goals') }}">Tus Metas</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_progress') }}">Tu Progreso</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_reminders') }}">Tus notificaciones</a>
                        </div>
                    </li>

                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                </div>
            </div>
        </nav>
  </div>



  </header>

  <main class="container my-5">
  <div class="container my-5">
    <h1 class="mb-4">Tus Datos Mindset</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Dato1</th>
          <th>Dato2</th>
          <th>Dato3</th>
          <th>Dato4</th>
          <th>Dato5</th>
        </tr>
      </thead>
      <tbody>
        {% for u in users %}
        <tr>
          <td>{{ u.idUser }}</td>
          <td>
            {{ u.userFirstName }}
            {{ u.userFirstLastName }}
          </td>
          <td>{{ u.userEmail }}</td>
          <td>{{ u.userAccountStatus }}</td>
          <td>{{ u.roleName }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </main>

    <footer>
      <div class="container text-center footer-container">
        <div class="row header-signature">
          <div class="col"></div>
          <div class="col"></div>
          <div class="col"></div>
          <div class="col-end">Mindset © 2025</div>
        </div>
      </div>
  </footer>
</body>
<script src = "{{ url_for('static', filename = 'js/bootstrap.min.js') }} "></script>
</html>

Version 1.4/ModelViewController/app/templates/user/userGoals.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/user/stylesUserInterface.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/footer.css') }}">
    <title>Tus datos</title>
</head>
<body>

 <div class="wrapper">
  <header> 
    <div class = "cabecero">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <img src="{{ url_for('static', filename='uploads/main/header/whitemindsetlogo.png') }}" alt="">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_dashboard') }}"> Tu inicio</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_data')}}">Tus datos</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_goals') }}">Tus Metas</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_progress') }}">Tu Progreso</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_reminders') }}">Tus notificaciones</a>
                        </div>
                    </li>

                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                </div>
            </div>
        </nav>
  </div>



  </header>

  <main class="container my-5">
  <div class="container my-5">
    <h1 class="mb-4">Tus Metas</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Dato1</th>
          <th>Dato2</th>
          <th>Dato3</th>
          <th>Dato4</th>
          <th>Dato5</th>
        </tr>
      </thead>
      <tbody>
        {% for u in users %}
        <tr>
          <td>{{ u.idUser }}</td>
          <td>
            {{ u.userFirstName }}
            {{ u.userFirstLastName }}
          </td>
          <td>{{ u.userEmail }}</td>
          <td>{{ u.userAccountStatus }}</td>
          <td>{{ u.roleName }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </main>

    <footer>
      <div class="container text-center footer-container">
        <div class="row header-signature">
          <div class="col"></div>
          <div class="col"></div>
          <div class="col"></div>
          <div class="col-end">Mindset © 2025</div>
        </div>
      </div>
  </footer>
</body>
<script src = "{{ url_for('static', filename = 'js/bootstrap.min.js') }} "></script>
</html>

Version 1.4/ModelViewController/app/templates/user/userInterface.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/user/stylesUserInterface.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/footer.css') }}">
    <title>Interfaz principal</title>
</head>
<body>

 <div class="wrapper">
  <header> 
    <div class = "cabecero">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <img src="{{ url_for('static', filename='uploads/main/header/whitemindsetlogo.png') }}" alt="">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="/Views/">Inicio</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="/Views/Interface/UserInterface.html">Tu Interfaz</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="/Views/mindset_actualizado/Frontend_isaura/indexseguimiento.html">Tu Progreso</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="/Views/minset/index.html">Pausas Activas</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="/Views/mindset_actualizado/Frontend_isaura/indexnotificaciones.html">Tus Recordatorios</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="/Views/InitialData/FormInitialData.html">Tus Datos Físicos</a>
                        </div>
                    </li>


                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                </div>
            </div>
        </nav>
  </div>



  </header>

  <main class="container my-5">
  <div class="row row-cols-1 row-cols-md-2 g-4">
  <div class="col">
    <div class="card">
      <img src="/Views/Interface/Media/PersonalProgress.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Tu perfil Mindset</h5>
        <p class="card-text">Tu perfil de usuario Mindset</p>
            <a href="#" class="btn btn-primary">¡Vamos!</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="/Views/Interface/Media/Reminders.webp" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Tus recordatorios (notificaciones)</h5>
        <p class="card-text">Mantente en sintonía con tus objetivos. Aquí encontrarás todos tus recordatorios para que nada se te escape.</p>
            <a href="#" class="btn btn-primary">¡Vamos!</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="/Views/Interface/Media/ActivePauses.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Tus pausas activas</h5>
        <p class="card-text">Recarga tu energía y mejora tu bienestar con momentos de movimiento y relajación. ¡Tu cuerpo y mente te lo agradecerán!</p>
            <a href="#" class="btn btn-primary">¡Vamos!</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="/Views/Interface/Media/PhysicalData.avif" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Tus Mediciones</h5>
        <p class="card-text">Conoce tus avances con datos precisos. Analiza, ajusta y optimiza tu rendimiento para alcanzar lo mejor de ti mismo.</p>
            <a href="#" class="btn btn-primary">¡Vamos!</a>
      </div>
    </div>
  </div>
</div>
  </main>

    <footer>
      <div class="container text-center footer-container">
        <div class="row header-signature">
          <div class="col"></div>
          <div class="col"></div>
          <div class="col"></div>
          <div class="col-end">Mindset © 2025</div>
        </div>
      </div>
  </footer>
</body>
<script src = "{{ url_for('static', filename = 'js/bootstrap.min.js') }} "></script>
</html>

Version 1.4/ModelViewController/app/templates/user/userProgress.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/user/stylesUserInterface.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main/footer.css') }}">
    <title>Tus datos</title>
</head>
<body>

 <div class="wrapper">
  <header> 
    <div class = "cabecero">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <img src="{{ url_for('static', filename='uploads/main/header/whitemindsetlogo.png') }}" alt="">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_dashboard') }}"> Tu inicio</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_data')}}">Tus datos</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_goals') }}">Tus Metas</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_progress') }}">Tu Progreso</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="NavigationButtom">
                            <a class="nav-link" href="{{ url_for ('userDb.user_reminders') }}">Tus notificaciones</a>
                        </div>
                    </li>

                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                </div>
            </div>
        </nav>
  </div>



  </header>

  <main class="container my-5">
  <div class="container my-5">
    <h1 class="mb-4">Tu progreso</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Dato1</th>
          <th>Dato2</th>
          <th>Dato3</th>
          <th>Dato4</th>
          <th>Dato5</th>
        </tr>
      </thead>
      <tbody>
        {% for u in users %}
        <tr>
          <td>{{ u.idUser }}</td>
          <td>
            {{ u.userFirstName }}
            {{ u.userFirstLastName }}
          </td>
          <td>{{ u.userEmail }}</td>
          <td>{{ u.userAccountStatus }}</td>
          <td>{{ u.roleName }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </main>

    <footer>
      <div class="container text-center footer-container">
        <div class="row header-signature">
          <div class="col"></div>
          <div class="col"></div>
          <div class="col"></div>
          <div class="col-end">Mindset © 2025</div>
        </div>
      </div>
  </footer>
</body>
<script src = "{{ url_for('static', filename = 'js/bootstrap.min.js') }} "></script>
</html>